const data = [
  {
    answer: "forsake; leave behind",
    cardId: "car1",
    fullMemorize: false,
    nextReview: "",
    question: "abandon",
    stage: "depo",
  },
  {
    answer: "dwell",
    cardId: "car2",
    fullMemorize: false,
    nextReview: "",
    question: "abide",
    stage: "depo",
  },
  {
    answer: "do away with",
    cardId: "car3",
    fullMemorize: false,
    nextReview: "",
    question: "abolish",
    stage: "depo",
  },
  {
    answer: "to or in a foreign country",
    cardId: "car4",
    fullMemorize: false,
    nextReview: "",
    question: "abroad",
    stage: "depo",
  },
  {
    answer: "take in a liquid",
    cardId: "car5",
    fullMemorize: false,
    nextReview: "",
    question: "absorb",
    stage: "depo",
  },
  {
    answer: "inconsistent with reason or logic or common sense",
    cardId: "car6",
    fullMemorize: false,
    nextReview: "",
    question: "absurd",
    stage: "depo",
  },
];
